Feature/create directories0
SyuniCode-Academy/G-1-1-project pull request #31
Opened 2023-03-31 11:06 UTC by AndranikGalstyan2006

2023-03-31 11:48 UTC, hayk105 approved these changes
ok

2023-03-31 11:48 UTC, hayk105 commented on andranik/images/github logo.png
replace name github_logo.png

2023-03-31 11:48 UTC, hayk105 commented on andranik/index.html
ուղղարկել չի ուղարկել ա 😂

2023-03-31 11:48 UTC, hayk105 commented on andranik/root_index.html
ուղղարկել չի ուղարկել ա

2023-04-02 20:19 UTC, Hakob-98 requested changes
The code written in the root_index.html file does not conform to the html standard

2023-04-03 14:47 UTC, iviWebStudio commented
merged via https://github.com/SyuniCode-Academy/G-1-1-project/pull/37

2023-04-03 14:47 UTC, closed without merging